### PR TITLE
Add tests for production 9, 10,16

### PR DESCRIPTION
**Pull request by Akatroj**
~~branched off from https://github.com/kkafar/graph-grammars/pull/31~~

pls just approve this, i don't want to do anything more for this project

### CODE REVIEW

**Review by kkafar — COMMENTED** [review]
Beside unit tests, see my review [here](https://github.com/kkafar/graph-grammars/pull/32), these changes look good.

**Comment by kkafar** [comment]
Hey, I've merged #35 introducing some conflicts with your PR. However, you can now restore all changes done to the `src/example` directory (#35 handles that), so half of them are gone right away.

And the same goes actually for `src/production` <-- you can just delete these changes or merge-in main and accept all incoming changes.

I would do it for you, as I force-merged #35 & #34 into the main, but you decided to open PR from your own fork & I can't push there, so you have to do it yourself.

**Review by kkafar — APPROVED** [review]
Yeah, I guess it would be much less work in case you just used `rev_mapping` from production to validate the changes 😅 

Looks good

**Comment by Akatroj** [comment]
@kkafar can you merge? I'm not a collaborator in this repo 😅

**Comment by kkafar** [comment]
yeah, sure

**Pull request merged**
